/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package org.d20CombatTracker.kotlin.lib

import kotlin.test.Test
import kotlin.test.assertEquals
import kotlin.test.assertTrue

class LibraryTest {
    @Test fun someLibraryMethodReturnsTrue() {
        val classUnderTest = Library()
        assertTrue(classUnderTest.someLibraryMethod(), "someLibraryMethod should return 'true'")
    }
    @Test fun someTextMethodReturnsHello() {
        val classUnderTest = Library()
        assertEquals("Hello!", classUnderTest.someTextMethod())
    }
}
